{% set version = "2.9.5" %}
{% set name = "pari" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://pari.math.u-bordeaux.fr/pub/pari/unix/{{ name }}-{{ version }}.tar.gz
  sha256: 6b451825b41d2f8b29592c08d671999527bf936789c599d77b8dfdc663f1e617
  patches:
    # Jeroen Demeyer - Add -fno-common to DLCFLAGS on
    # Darwin. Submitted upstream, but upstream only applied it for PowerPC.
    # Since this doesn't break anything and only improves performance, add
    # the flag unconditionally
    - patches/get_dlcflags.patch
    # Jeroen Demeyer - Use PROT_NONE for unused virtual stack memory
    - patches/prot_none.patch
    # Jeroen Demeyer - https://trac.sagemath.org/ticket/19883
    # do not display warnings regarding the stack size (unless DEBUGMEM is set).
    - patches/stackwarn.patch

build:
  number: 1002
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('pari', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - curl
  host:
    - gmp
    - readline
    - openssl
    - perl
  run:
    - gmp
    - readline
    - perl

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/include/{{ name }}/anal.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://pari.math.u-bordeaux.fr
  license: GPLv2+
  license_file: {{ SRC_DIR }}/COPYING
  summary: PARI/GP is a widely used computer algebra system designed for fast computations in number theory
  dev_url: http://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi
  doc_url: http://pari.math.u-bordeaux.fr/dochtml/html-stable/

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
