{% set version = "2.17.2" %}
{% set name = "pari" %}
{% set build_num = "4" %}
{% set posix = "m2-" if build_platform.startswith("win-") else '' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:
    - http://pari.math.u-bordeaux.fr/pub/pari/unix/{{ name }}-{{ version }}.tar.gz
    - http://pari.math.u-bordeaux.fr/pub/pari/OLD/{{ version.split('.')[:2] | join('.') }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d30578f5cf97b137a281f4548d131aafc0cde86bcfd10cc1e1bd72a81e65061
  patches:
    - patches/0001-Make-Configure-script-verbose.patch
    - patches/0002-Set-RUNTEST-echo-when-cross-compiling.patch  # [build_platform != target_platform]
    - patches/0003-Do-not-run-get_double_format-when-cross-compiling.patch  # [build_platform != target_platform]
    # Do not check for GMP. The script fails to detect our GMP in the
    # conda-prefix. (And it also does not work when cross-compiling.)
    - patches/0004-Do-not-run-get_gmp-when-cross-compiling.patch
    # Do not check for readline. The script fails to detect our readline in the
    # conda-prefix. (And it also does not work when cross-compiling.)
    - patches/0005-Do-not-run-get_readline-when-cross-compiling.patch
    - patches/0006-Fix-config-objdir-when-cross-compiling.patch  # [build_platform != target_platform]
    # Patches from sagemath
    - patches/get_dlcflags.patch
    # - patches/prot_none_cygwin.patch
    - patches/pari_mainstack.diff

build:
  number: {{ build_num }}
  string: h{{ PKG_HASH }}_{{ build_num }}_{{ variant }}
  run_exports:
    - {{ pin_subpackage('pari', max_pin='x.x') }}
    - pari * *_{{ variant }}

requirements:
  build:
    - {{ compiler("c") }}          # [unix]
    - {{ stdlib("c") }}            # [unix]
    - {{ compiler("m2w64_c") }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}base        # [build_platform.startswith("win-")]
    - {{ posix }}diffutils   # [build_platform.startswith("win-")]
    - curl
    - {{ posix }}make
    - bison         # [unix]
    - winflexbison  # [win]
    - perl 5.*
  host:
    - gmp
    - readline  # [unix]
    - openssl
  run:
    - perl 5.*
    - pari-galdata
    - pari-seadata-small

test:
  commands:
    - test -f ${PREFIX}/include/pari/pari.h                                # [unix]
    - test -f ${PREFIX}/include/pari/anal.h                                # [unix]
    - test -f ${PREFIX}/lib/libpari.a                                      # [unix]
    - test -f ${PREFIX}/lib/libpari${SHLIB_EXT}                            # [unix]
    - test -f ${PREFIX}/lib/libpari-gmp${SHLIB_EXT}                        # [osx and variant == "single"]
    - test -f ${PREFIX}/lib/libpari-gmp-tls${SHLIB_EXT}                    # [osx and variant == "pthread"]
    - test -f ${PREFIX}/lib/libpari-gmp${SHLIB_EXT}.{{ version }}          # [linux and variant == "single"]
    - test -f ${PREFIX}/lib/libpari-gmp-tls${SHLIB_EXT}.{{ version }}      # [linux and variant == "pthread"]
    - if not exist %LIBRARY_INC%\pari\pari.h exit 1                        # [win]
    - if not exist %LIBRARY_INC%\pari\anal.h exit 1                        # [win]
    - if not exist %LIBRARY_BIN%\libpari.dll exit 1                        # [win]
    - if not exist %LIBRARY_BIN%\libpari-gmp.dll exit 1                    # [win and variant == "single"]
    - if not exist %LIBRARY_BIN%\libpari-gmp-tls.dll exit 1                # [win and variant == "pthread"]

about:
  home: http://pari.math.u-bordeaux.fr
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: PARI/GP is a widely used computer algebra system designed for fast computations in number theory
  dev_url: http://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi
  doc_url: http://pari.math.u-bordeaux.fr/dochtml/html-stable/

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
