{% set version = "2.17.0" %}
{% set name = "pari" %}
{% set build_num = "2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:
    - http://pari.math.u-bordeaux.fr/pub/pari/unix/{{ name }}-{{ version }}.tar.gz
    - http://pari.math.u-bordeaux.fr/pub/pari/OLD/{{ version.split('.')[:2] | join('.') }}/{{ name }}-{{ version }}.tar.gz
  sha256: e723e7cef18d08c6ece2283af9a9b4d56077c22b4fce998faaa588d389b1aea8
  patches:
    - 0001-Make-Configure-script-verbose.patch
    - 0002-Do-not-run-get_cc-when-cross-compiling.patch  # [build_platform != target_platform]
    - 0003-Do-not-run-get_double_format-when-cross-compiling.patch  # [build_platform != target_platform]
    - 0004-Do-not-run-get_gmp-when-cross-compiling.patch  # [build_platform != target_platform]
    - 0005-Do-not-run-get_readline-when-cross-compiling.patch  # [build_platform != target_platform]
    # Patches from sagemath
    - patches/get_dlcflags.patch
    # - patches/prot_none_cygwin.patch
    - patches/pari_mainstack.diff

build:
  number: {{ build_num }}
  skip: true  # [win]
  string: h{{ PKG_HASH }}_{{ build_num }}_{{ variant }}
  run_exports:
    - {{ pin_subpackage('pari', max_pin='x.x') }}
    - pari * *_{{ variant }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libtool
    - curl
    - make
    - perl 5.*
  host:
    - gmp
    - readline
    - openssl
  run:
    - readline
    - perl 5.*
    - pari-galdata
    - pari-seadata-small

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/include/{{ name }}/anal.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

about:
  home: http://pari.math.u-bordeaux.fr
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: PARI/GP is a widely used computer algebra system designed for fast computations in number theory
  dev_url: http://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi
  doc_url: http://pari.math.u-bordeaux.fr/dochtml/html-stable/

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
