appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: bnbzpb7Pq3undPw8DJ+lToYFd3d8mDFvD1D4BJkHmAv7F23PcJ3vTLhxezr+GtNBn1yMNSE5pqCkWq9I2fAD0LmRzgjQqLWb5Jtzwh+IUYtZLZJCMchULWIqQaK4tI+ZFoa+YdomYiobNz1wN9NFxjlMG5gFucZaM+dRyw1/ZkOmZuIFXMrePvAPc7lKjA92CFg+P8+/NawlZ7P73eRZVS29OvNYXkfuZHRtaHEYKsMAFq4wis9Jg4mjewoReXBlXnpACqfurqBoVIA5UqSlpPAoy0TYPBvCqY7rLsPxjIErEf1Blw8ujJgrsO2woHslioHyyeG5KA5grYMqamJy4wDPsk3NLIKAb+reatYKO9A0AmAj++VwV0Z4Fgncn9deUEebdJ2/Xazk90WrGZxm8UQnwBfXxzgkN8KLW7NpmkNe4oOKqGhGUT69reZE/oxA2xnAybbUo+Osre5K24+86m5RWRaZHZiKzfR1eikg32ojIAb8d7jCKgHJGqbIlzd4J1VLdVf+mgoKHZr+980PvNKgaSuFnx3HyoTHfTkwe2RG0am4C2951Qqs+CBnnR9p29PbrlJOEBiONuylmT0zv89s3o2iRSE/qYAKlsIis5CMdtNFRTDupAuHFBr35vhOAKA9+RyKFVh2TbjQHkAGKhF9QXxyAGh03eApOgWldq4=}
conda_forge_output_validation: true
